# Generated by Django 4.1.3 on 2022-11-16 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppPaginaWeb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='juegos',
            name='publicacion',
        ),
        migrations.RemoveField(
            model_name='libros',
            name='publicacion',
        ),
        migrations.RemoveField(
            model_name='series',
            name='estreno',
        ),
    ]
